### PR TITLE
Use write() instead of end() on the output stream

### PR DESCRIPTION
**Pull request by rads**
This avoids errors when the output stream is `process.stdin`.

### CODE REVIEW

**Comment by TooTallNate** [comment]
I'm down, but we still need an `.end()` call for the non-`process.stdin` scenario. Perhaps:

``` js
try {
  output.end();
} catch (e) { /* ignore */ }
```

After the `write()` call?

**Comment by gcorne** [comment]
Can we get this fixed and released so that we can merge https://github.com/Automattic/calypso-pre-oss/issues/1303?

**Comment by rads** [comment]
I updated the commit to just handle the file output and stdout stream cases separately. It should be good to go now.

**Comment by TooTallNate** [comment]
I liked the stream-oriented aspect of the code before, but since we have to special-case `process.stdout` anyways, then this is fine IMO.

**Pull request merged**
